Repository codezonediitj/adaboost, pull requests merged in 2020-03, with the labels that each got.

#11 Added "git clone" as a command in README
  README.md
Labels: beginner, documentation

#14 Minor updates to README
  README.md
Labels: documentation

#17 Update README.md
  README.md
Labels: documentation

#16 Windows support to read me added
  README.md
Labels: documentation

#18 documentation for cuda_wrappers done
  adaboost/utils/cuda_wrappers.hpp
Labels: documentation, utils
